
var headConfigs = module.exports.headConfigs = {
/*
    js_engine:{
        src: [
            '/js/engine/hash.js'
            ,'/js/engine/start.js'
            ,'/js/engine/public.js'
            ,'/js/engine/get_text.js'
            ,'/js/engine/mutation.js'
            ,'/js/engine/widget.js'
            ,'/js/engine/bidi.js'
            ,'/js/engine/player_recorder.js'
            ,'/js/engine/end.js'
        ],
        final:'/js/bablic.js',
        type:'js',
        name:'engine'
    },
    js_omg:{
        type:'js',
        name:'omg',
        src:[
            '/js/lib/jquery-ui-1.8.23.custom.min.js',
            '/js/site/omg.js'
        ]
    },
    js_snippet:{
        type:'js',
        name:'snippet',
        src:[
            '/js/engine/snippet.js'
        ]
    },
    js_wizard:{
        type:'js',
        name:'wizard',
        min:false,
        src:[
            '/js/lib/jquery-site.js'
            ,'/js/lib/jquery-ui-1.10.1.custom.min.js'
            ,'/js/lib/response.min.js'
            ,'/js/lib/file-uploader.js'
            ,'/js/lib/knockout-2.1.0.js'
            ,'/js/lib/ko-autocomplete.js'
            ,'/js/lib/ko-simplegrid.js'
            ,'/js/lib/jquery.clipboard.min.js'
            ,'/js/lib/jquery.colorbox-min.js'
            ,'/js/lib/jquery.validate.min.js'
            ,'/js/lib/worldmap.js'
            ,'/js/lib/socket.io.min.js',
            ,'/js/site/map.js'
            ,'/js/site/popups.js'
            ,'/js/site/site.js'
            ,'/js/script.js'
            ,'/js/site/wizard/details.js'
            ,'/js/site/wizard/payment.js'
            ,'/js/site/wizard/plans.js'
            ,'/js/site/wizard/scanning.js'
            ,'/js/site/wizard/wizard.js'
        ]
    },
*/

    js_includes:{
        type:'js',
        name:'includes',
        min:false,
        final:'/dist/js/built.js',
        src:[
            'deliver/public/js/jquerypp/jquery-1.8.2.min.js',
            'deliver/public/js/jquerypp/jquery-ui-1.9.1.custom.min.js',
            'deliver/public/js/lib/dust-full-0.3.0.js',
            'deliver/public/js/InfoBox.js',
            'deliver/public/js/lib/fileuploader.js',
            'deliver/public/js/imgscale.jquery.min.js',
            'deliver/public/js/jquerypp/jqtouch.min.js',
            'deliver/public/js/jquerypp/jquery-fieldselection.js',
            'deliver/public/js/jquerypp/jquery.autoellipsis-1.0.8.min.js',
            'deliver/public/js/jquerypp/jquery.colorbox-min.js',
            'deliver/public/js/jquerypp/jquery.cycle.all.js',
            'deliver/public/js/jquerypp/jquery.easing.1.3.js',
            'deliver/public/js/jquerypp/jquery.placeholder.min.js',
            'deliver/public/js/jquerypp/jquery.tools.min.js',
            'deliver/public/js/jquerypp/jquery.tooltip.min.js',
            'deliver/public/js/jquerypp/jquery.validate.min.js',
            'deliver/public/js/jquerypp/jquery.compare.js',
            'deliver/public/js/jquerypp/jquery.range.js',
            'deliver/public/js/jquerypp/jquery.selection.js',
            'deliver/public/js/lib/date.format.js',
            'deliver/public/js/select2.js',
            /*'/plugins/ckeditor/ckeditor.js',
            '/plugins/ckeditor/adapters/jquery.js',*/

            'deliver/public/js/compiled_templates.js',
            'deliver/public/js/common.js',
            'deliver/public/js/db.js',
            'deliver/public/js/fb.js',
            'deliver/public/js/lib/search.js',
            'deliver/public/js/timeline.js',
            'deliver/public/js/tokensbar_model.js',
            'deliver/public/js/listCommon.js',
            'deliver/public/js/popupProvider.js',
            'deliver/public/js/proxy_common.js',
            'deliver/public/js/lib/maps.js',

            '/js/jquerypp/jquery.movingboxes.js',
            '/js/jquery.cookie.js',
            '/js/storyjs-embed.js',
            /*'/js/jquerypp/jquery.dotdotdot-1.5.6-packed.js'*/
        ]
    },
  /*
    css_wizard:{
        type:'css',
        name:'wizard',
        min:false,
        src:[
            '/css/reset.css'
            ,'/css/ui-lightness/jquery-ui-1.8.22.custom.css'
            ,'/css/style.css'
            ,'/css/fonts.css'
            ,'/css/console.css'
            ,'/css/header.css'
            ,'/css/wizard.css'
        ]
    },
    js_site:{
        type:'js',
        name:'site',
        min:false,
        src:[
            *//*'/js/lib/jquery-site.js'
            ,'/js/lib/jquery-ui-1.10.1.custom.min.js'
            ,'/js/lib/response.min.js'
            ,'/js/lib/file-uploader.js'
            ,'/js/lib/knockout-2.1.0.js'
            ,'/js/lib/ko-autocomplete.js'
            ,'/js/lib/ko-simplegrid.js'
            ,'/js/lib/jquery.clipboard.min.js'
            ,'/js/lib/jquery.colorbox-min.js'
            ,'/js/lib/jquery.validate.min.js'
            ,'/js/lib/worldmap.js'
            ,'/js/lib/socket.io.min.js',
            ,'/js/site/map.js'
            ,'/js/site/console/dashboard.js'
            ,'/js/site/console/review.js'
            ,'/js/site/console/settings.js'
            ,'/js/site/console/roles.js'
            ,'/js/site/console/billing.js'
            ,'/js/site/console/pages.js'
            ,'/js/site/console/logs.js'
            ,'/js/site/console/social-translation.js'
            ,'/js/site/console/console-client.js'
            ,'/js/site/popups.js'
            ,'/js/site/site.js'
            ,'/js/script.js'
            ,'/js/site/new-site.js'
            ,'/js/site/signup.js'*//*
            '\js\common.js',
            '\js\db.js',
            '\js\fb.js',
            '\js\listCommon.js',
            '\js\maps.js',
            '\js\popupProvider.js',
            '\js\proxy_common.js',
            '\js\select2.js',
            '\js\social_common.js',
            '\js\social_common.js',
        ]
    },
    css_site:{
        type:'css',
        name:'site',
        min:false,
        src:[
            '/css/reset.css'
            ,'/css/ui-lightness/jquery-ui-1.8.22.custom.css'
            ,'/css/wizard.css'
            ,'/css/style.css'
            ,'/css/fonts.css'
            ,'/css/console.css'
            ,'/css/header.css'
        ],
        final:'/css/site.dist.css'
    },
    css_homepage:{
        type:'css',
        name:'homepage',
        min:false,
        src:[
            '/css/all.css'
            ,'/css/header.css'
            ,'/css/fonts.css'
            ,'/css/new-home.css'
        ]
    },
    css_omg:{
        type:'css',
        name:'omg',
        min:false,
        src:[
            '/css/omg.css'
        ]
    },
    js_context:{
        type:'js',
        name:'context',
        src:[
            '/js/lib/jquery-site.js',
            '/js/site/context.js'
        ]
    },
    js_widget:{
        type:'js',
        name:'widget',
        src:[
            '/js/lib/jquery-site.js',
            '/js/site/console/widget.js',
            '/js/engine/widget.js'
        ]
    },
    css_widget:{
        type:'css',
        name:'widget',
        src:[
            '/css/widget.css'
        ]
    }
*/
};

module.exports.WARNING_QUOTA_FACTOR = 0.9;